services:
  db:
    image: postgres:alpine3.18
    container_name: "django-db"
    expose: 
      - "5432"
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ../db/database:/var/lib/postgresql/data
      - ../db/init:/docker-entrypoint-initdb.d  
  web:
    image: django/web:1.0
    build: ./web
    container_name: "django-web"
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
    depends_on:
      - db
    stdin_open: true
    tty: true
    volumes:
      - ../web:/home/user1/dev
 