[loggers]
keys=root

[handlers]
keys=fileHandler, stdoutHandler

[formatters]
keys=fmt1

[logger_root]
level=INFO # DEBUG から INFO に変更 (任意、通常運用ではINFOが多い)
handlers=fileHandler, stdoutHandler

[handler_fileHandler]
class=FileHandler
formatter=fmt1
args=('./out/sample.log','a') 

[handler_stdoutHandler]
class=StreamHandler
formatter=fmt1
args=(sys.stdout,)

[formatter_fmt1]
format=[%(asctime)s]%(levelname)-8s%(name)s(%(lineno)d): %(message)s # レベル名も表示
datefmt=%Y-%m-%d %H:%M:%S